"""
Port the static Lamplight Cinema build into this Next.js app.

Reads the verified single-file site (SRC), scopes its CSS under #eng,
converts the markup to JSX, injects the Site Editor's content overrides
(app/lib/editable.json), swaps the demo form handler for the real intake
server action, and writes app/engraved.css + app/HomeClient.tsx.

Run from the repo root:  python scripts/port.py
The static file remains the design source of truth; app/page.tsx (the
server wrapper that fetches overrides) is hand-maintained, not generated.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(r"C:/Users/trevo/OneDrive/Desktop/AI Websites/higgins/index.html")

src = SRC.read_text(encoding="utf-8")
manifest = json.loads((ROOT / "app/lib/editable.json").read_text(encoding="utf-8"))

# ---------- CSS: scope every selector under #eng ----------
css = src.split("<style>")[1].split("</style>")[0]

def scope_selector(sel: str) -> str:
    sel = sel.strip()
    if not sel:
        return sel
    if sel.startswith("#eng"):
        return sel
    if sel == ":root" or sel == "body":
        return "#eng"
    if sel.startswith("body::after"):
        return "#eng::after"
    if sel.startswith("body.printing") or sel.startswith("body:not(.printing"):
        return sel
    if sel.startswith("::selection"):
        return "#eng ::selection"
    if sel.startswith("html.js"):
        return sel.replace("html.js ", "html.js #eng ", 1)
    if sel.startswith("html.no-io"):
        return sel.replace("html.no-io ", "html.no-io #eng ", 1)
    if sel == "html" or sel.startswith("*"):
        return sel
    return "#eng " + sel

out, in_kf, depth = [], 0, 0
for line in css.split("\n"):
    stripped = line.strip()
    if in_kf:
        out.append(line)
        depth += line.count("{") - line.count("}")
        if depth <= 0:
            in_kf = 0
        continue
    if stripped.startswith("@keyframes"):
        in_kf = 1
        depth = line.count("{") - line.count("}")
        out.append(line)
        continue
    if stripped.startswith("@media") or stripped.startswith("@supports"):
        out.append(line)
        continue
    if "{" in line and not stripped.startswith("/*") and not stripped.startswith("@"):
        selpart, rest = line.split("{", 1)
        out.append(",".join(scope_selector(s) for s in selpart.split(",")) + "{" + rest)
        continue
    out.append(line)

css2 = "\n".join(out)
css2 = css2.replace(
    ":root{--mobbar:calc(66px + env(safe-area-inset-bottom))}",
    "#eng{--mobbar:calc(66px + env(safe-area-inset-bottom))}",
)
css2 = css2.replace("--fd:'Marcellus','Times New Roman',serif;", "--fd:var(--font-marcellus),'Times New Roman',serif;")
css2 = css2.replace("--fb:'Cormorant Garamond',Georgia,serif;", "--fb:var(--font-cormorant),Georgia,serif;")
css2 = css2.replace("--fu:'Archivo',system-ui,sans-serif;", "--fu:var(--font-archivo),system-ui,sans-serif;")
(ROOT / "app/engraved.css").write_text(
    "/* LAMPLIGHT CINEMA design system, scoped under #eng so /updates and /admin keep their own styling.\n"
    "   GENERATED by scripts/port.py from the static build. Do not hand-edit. */\n" + css2,
    encoding="utf-8",
)

# ---------- HTML body -> JSX ----------
body = src.split("<body>")[1].split("<script>")[0]
jsx = re.sub(r"<!--.*?-->", "", body, flags=re.S)
jsx = jsx.replace(' class="', ' className="').replace(' for="', ' htmlFor="')
jsx = jsx.replace(' tabindex="-1"', " tabIndex={-1}")
jsx = jsx.replace(' fetchpriority="high"', ' fetchPriority="high"')
jsx = jsx.replace(' autocomplete="', ' autoComplete="')
jsx = jsx.replace(" noValidate>", " noValidate={true}>")

def style_to_obj(m):
    props = []
    for d in [d for d in m.group(1).split(";") if d.strip()]:
        k, v = d.split(":", 1)
        k = re.sub(r"-([a-z])", lambda mm: mm.group(1).upper(), k.strip())
        props.append(f"{k}:'{v.strip()}'")
    return " style={{" + ",".join(props) + "}}"

jsx = re.sub(r' style="([^"]*)"', style_to_obj, jsx)
jsx = re.sub(r"<(img|input|br|hr)([^>]*?)\s*/?>", lambda m: f"<{m.group(1)}{m.group(2)} />", jsx)
jsx = jsx.replace('src="assets/', 'src="/assets/')

# ---------- Inject Site Editor overrides ----------
missing = []
for field in manifest:
    src_text = field["src"]
    expr = "{c[" + json.dumps(field["key"]) + "] ?? " + json.dumps(src_text) + "}"
    if ">" + src_text + "<" in jsx:
        jsx = jsx.replace(">" + src_text + "<", ">" + expr + "<", 1)
    else:
        missing.append(field["key"])
if missing:
    raise SystemExit(f"editable.json src text not found in static build: {missing}")

# ---------- Runtime JS: strip demo form handler, keep the rest ----------
js = src.split("<script>\n")[1].split("\n</script>")[0]
js, n = re.subn(
    r"/\* FORM · DEMO ONLY.*?\}\)\(\);\n?",
    "/* form handling moved to React (real intake) -- see below */\n",
    js,
    flags=re.S,
)
if n != 1:
    raise SystemExit("demo form handler not found in static build JS")

FORM_JS = """
    /* FORM -> intake table via server action (the real one) */
    const cf = document.getElementById('cf'), fm = document.getElementById('fm');
    if (cf && fm) cf.addEventListener('submit', async (e) => {
      e.preventDefault();
      const form = cf;
      if (!form.checkValidity()) { form.reportValidity(); return; }
      const btn = form.querySelector('button[type="submit"]');
      if (btn) { btn.disabled = true; btn.textContent = 'Sending'; }
      const fd = new FormData(form);
      let ok = false;
      try {
        const r = await submitIntake({
          name: fd.get('name'), tel: fd.get('tel'),
          email: fd.get('email'), message: fd.get('message'),
        });
        ok = !!(r && r.ok);
      } catch {}
      form.style.display = 'none'; fm.style.display = 'block';
      fm.innerHTML = ok
        ? 'Thank you. Your message is in at the office and will be waiting when we open, Monday to Friday at 8:00 AM. If this cannot wait, call <a href="tel:+13184734250">318.473.4250</a>.'
        : 'Something interrupted the send. Please call <a href="tel:+13184734250">318.473.4250</a>, or email the office, so nothing slips.';
      fm.focus();
    });
"""

guard = (
    "    if (document.documentElement.dataset.engInit) return;\n"
    "    document.documentElement.dataset.engInit = '1';\n"
)
page = (
    "// @ts-nocheck -- GENERATED by scripts/port.py from the verified static build.\n"
    "// The runtime script is kept verbatim so tested behavior stays identical.\n"
    '"use client";\n\n'
    'import { useEffect } from "react";\n'
    'import { submitIntake } from "./actions/intake";\n'
    'import "./engraved.css";\n\n'
    "export default function HomeClient({ c }: { c: Record<string, string> }) {\n"
    "  useEffect(() => {\n" + guard + js + "\n" + FORM_JS + "\n  }, []);\n\n"
    '  return (\n    <div id="eng">\n' + jsx.strip() + "\n    </div>\n  );\n}\n"
)
(ROOT / "app/HomeClient.tsx").write_text(page, encoding="utf-8")
print("port complete: app/engraved.css + app/HomeClient.tsx")
